# Generated by Django 5.2.8 on 2025-11-07 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('nahw', 'Syntax'), ('sarf', 'Morphology'), ('balagha', 'Rhetoric')], max_length=20)),
                ('arabic_description', models.TextField()),
                ('english_description', models.TextField()),
                ('yoruba_description', models.TextField(blank=True)),
                ('examples', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grammar_rules',
                'ordering': ['difficulty_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OCRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ocr_scans/')),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Response')], max_length=10)),
                ('content', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.ocrscan')),
            ],
            options={
                'db_table': 'chat_interactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_breakdown', models.JSONField()),
                ('english_translation', models.TextField()),
                ('yoruba_translation', models.TextField(blank=True)),
                ('grammar_points', models.JSONField(default=list)),
                ('vocabulary_highlight', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.ocrscan')),
            ],
            options={
                'verbose_name_plural': 'Text Analyses',
                'db_table': 'text_analyses',
            },
        ),
        migrations.CreateModel(
            name='AudioTTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='tts_audio/')),
                ('audio_base64', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='core.textanalysis')),
            ],
            options={
                'verbose_name_plural': 'Audio TTS',
                'db_table': 'audio_tts',
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_word', models.CharField(max_length=255)),
                ('transliteration', models.CharField(max_length=255)),
                ('english_meaning', models.TextField()),
                ('yoruba_meaning', models.TextField(blank=True)),
                ('word_type', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('particle', 'Particle'), ('phrase', 'Phrase')], max_length=20)),
                ('root_letters', models.CharField(blank=True, max_length=50)),
                ('grammar_notes', models.TextField(blank=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('difficulty_level', models.CharField(default='beginner', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vocabulary_words',
                'ordering': ['arabic_word'],
                'unique_together': {('arabic_word', 'transliteration')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('listening', 'Listening')], max_length=20)),
                ('description', models.TextField()),
                ('content', models.JSONField()),
                ('difficulty_level', models.CharField(default='beginner', max_length=20)),
                ('estimated_duration', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grammar_rules', models.ManyToManyField(blank=True, to='core.grammarrule')),
                ('vocabulary_words', models.ManyToManyField(blank=True, to='core.vocabularyword')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='grammarrule',
            name='related_vocabulary',
            field=models.ManyToManyField(blank=True, to='core.vocabularyword'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_encountered', models.IntegerField(default=1)),
                ('times_correct', models.IntegerField(default=0)),
                ('mastery_level', models.IntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vocabularyword')),
            ],
            options={
                'verbose_name_plural': 'User Progress',
                'db_table': 'user_progress',
                'unique_together': {('user', 'vocabulary_word')},
            },
        ),
    ]
